import { reactive } from 'vue'

export const store = reactive({
    thirdCards: [
        {
            img: '../src/assets/img/event1.jpg',
            title: 'Toronto Cycling Event 2023',
            date: '2022-06-22 @ 01:30 - 2024-08-23 @ 07:00',
            location: 'Toronto',
            bike: 'Bicycle Race',
            numberClip: '22',
            monthClip: 'JUN',
        },
        {
            img: '../src/assets/img/event2.jpg',
            title: 'Istanbul Cycling Event 2023',
            date: '2022-06-30 @ 01:30 - 2024-10-19 @ 03:30',
            location: 'Istanbul',
            bike: 'Bike Sport',
            numberClip: '30',
            monthClip: 'JUN',
        },
        {
            img: '../src/assets/img/event2.jpg',
            title: 'Istanbul Cycling Event 2023',
            date: '2022-06-30 @ 01:30 - 2024-10-19 @ 03:30',
            location: 'Istanbul',
            bike: 'Bike Sport',
            numberClip: '30',
            monthClip: 'JUN',
        },
        {
            img: '../src/assets/img/event2.jpg',
            title: 'Istanbul Cycling Event 2023',
            date: '2022-06-30 @ 01:30 - 2024-10-19 @ 03:30',
            location: 'Istanbul',
            bike: 'Bike Sport',
            numberClip: '30',
            monthClip: 'JUN',
        },
        {
            img: '../src/assets/img/event2.jpg',
            title: 'Istanbul Cycling Event 2023',
            date: '2022-06-30 @ 01:30 - 2024-10-19 @ 03:30',
            location: 'Istanbul',
            bike: 'Bike Sport',
            numberClip: '30',
            monthClip: 'JUN',
        },
        {
            img: '../src/assets/img/event2.jpg',
            title: 'Istanbul Cycling Event 2023',
            date: '2022-06-30 @ 01:30 - 2024-10-19 @ 03:30',
            location: 'Istanbul',
            bike: 'Bike Sport',
            numberClip: '30',
            monthClip: 'JUN',
        },
        {
            img: '../src/assets/img/event2.jpg',
            title: 'Istanbul Cycling Event 2023',
            date: '2022-06-30 @ 01:30 - 2024-10-19 @ 03:30',
            location: 'Istanbul',
            bike: 'Bike Sport',
            numberClip: '30',
            monthClip: 'JUN',
        },
        {
            img: '../src/assets/img/event2.jpg',
            title: 'Istanbul Cycling Event 2023',
            date: '2022-06-30 @ 01:30 - 2024-10-19 @ 03:30',
            location: 'Istanbul',
            bike: 'Bike Sport',
            numberClip: '30',
            monthClip: 'JUN',
        },
        {
            img: '../src/assets/img/event2.jpg',
            title: 'Istanbul Cycling Event 2023',
            date: '2022-06-30 @ 01:30 - 2024-10-19 @ 03:30',
            location: 'Istanbul',
            bike: 'Bike Sport',
            numberClip: '30',
            monthClip: 'JUN',
        },
        {
            img: '../src/assets/img/event2.jpg',
            title: 'Istanbul Cycling Event 2023',
            date: '2022-06-30 @ 01:30 - 2024-10-19 @ 03:30',
            location: 'Istanbul',
            bike: 'Bike Sport',
            numberClip: '30',
            monthClip: 'JUN',
        },
    ]
});